### ISSUE TITLE
Broken Links to ac.zip and gp.zip

### ISSUE THREAD

**Issue by RaghavRao** [Stanford-STAGES/stanford-stages#10]
Following the links in the Readme for the ML files goes to the web hosting page (BlueHost), ac.zip and gp.zip can no longer be found there. 

Attached is the screen-shot I see when visiting the link for ac.zip

![Screenshot from 2020-01-23 15-10-50](https://user-images.githubusercontent.com/6820307/73019949-9d614900-3df2-11ea-8f1a-ceb90a03dcc5.png)

**Comment by informaton** [comment]
Thanks for the note.  The link should be working again now.  I'll leave the issue open as we should have a second mirror site to hosting these files to minimize potential downtime in the future.

**Comment by RaghavRao** [comment]
Unfortunately the link still doesn't work, I get a 500 response now (Internal Server Error)

**Comment by informaton** [comment]
This issue has been resolved to the extent that the files are downloadable (i.e. see #13).
